### ISSUE TITLE
Cannot find boot.json when starting localnode

### ISSUE THREAD

**Issue by ocknamo** [namuyan/bc4py#38]
## Bug(I guess)

I am trying to start local node mode. 
However, it is throwing the following errors.

Error
```
FileNotFoundError: Cannot find boot.json "/home/p2p/blockchain-py/bc4py/user/boot.json" or "/home/p2p/blockchain-py/2000/boot.json" ?
```

But, I can start public node in same environment.

## Versions
ver: 0.0.28-alpha, chain-ver=0
python3, python : 3.7.4
pip : 19.2.3

### code
``` shell script
~/blockchain-py$ python3 localnode.py
```

**Comment by namuyan** [comment]
Hello, you may lack of **boot.json**, genesis block data.
1. check [How to join testnet (JP)](https://hackmd.io/qUYkWVGoRuyATyLth_B6YQ)
2. write down to boot.json https://pastebin.com/UeRRqNmZ

**Comment by ocknamo** [comment]
Thanks. 
But I had boot.json in blockchain-py directory.

![image](https://user-images.githubusercontent.com/28864753/64946534-13d2c500-d8ae-11e9-939a-73fc5a9f387f.png)

I think this is the location specified in the tutorial.

Next, I got boot.json in blockchain-py/bc4py/user directory.
I can start localnode now.
The problem has been solved.

thank you.
